version: "3.8"

volumes:
  mkdocs-py:

services:
  mkdocs-image:
    image: python:3.9
    container_name: mkdocs-image
    restart: always
    volumes:
      - ./docs:/tmp/
      - ./requirements.txt:/tmp/requirements.txt  # Corrected: Changed 'do/requirements.txt' to './requirements.txt'
      - ./mkdocs.yml:/tmp/mkdocs.yml
    working_dir: /tmp  # Set the working directory within the container
    tty: true


