site_name: My Docs
site_author: My Docs for Python
nav:
    - Home: index.md
    - Usage: usage.md
    - For eg: for_eg.md
    - Tools: tools.md
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - content.code.annotate
    - navigation.index
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Roboto
    code: Roboto Mono