site_name: My Docs
site_author: My Docs for Python
nav:
    - Home: index.md
    - Usage: usage.md
    - For eg: for_eg.md
    - Tools: tools.md
    - Git cheat: git_cheat_cmd.md
    - Source Code: sourcecode.md
    - DevOps: k8op.md
    - Computer Networking: networking.md
theme:
  name: readthedocs
  language: en
#   features:
#     - navigation.instant
#     - navigation.index
#     - navigation.tabs.sticky
#     - content.action.edit
#     - content.action.view
#     - content.code.annotate
#     - content.code.copy
#     # - content.tabs.link
#     - content.tooltips
#     # - header.autohide
#     # - navigation.expand
#     - navigation.footer
#     - navigation.indexes
#     # - navigation.instant
#     # - navigation.prune
#     - navigation.sections
#     - navigation.tabs
#     # - navigation.tabs.sticky
#     - navigation.top
#     - navigation.tracking
#     - search.highlight
#     - search.share
#     - search.suggest
#     - toc.follow
#   palette:
#     - scheme: default
#       primary: indigo
#       accent: indigo
#       toggle:
#         icon: material/brightness-7
#         name: Switch to dark mode
#     - scheme: slate
#       primary: indigo
#       accent: indigo
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode
#   font:
#     text: Roboto
#     code: Roboto Mono
# plugins:
#   - mike
#   - search:
#       separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
#   - mkdocstrings