apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:                           #data: actual contents the key-value pairs
  database_url: mongodb-service #database url here is mongo-service as, we configure in service.yaml