apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=     #username is username, base64 
    mongo-root-password: cGFzc3dvcmQ=      #password is password, base64
