##Dockerfile for devcontainer

ARG version:"3.9"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${version}

# uncomment to Install git and other dependencies if required
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \ 
#     && apt-get install -y <add-package-here> && rm -rf /var/lib/apt/lists/*

USER botlar4