---
apiVersion: apps/v1
kind: Deployment  #kubernetes object
metadata:
  name: pod-info-deployment 
  namespace: development   #mention namespace to deploy this yaml 
  labels:
    app: pod-info  #name/label of pods that get created
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-info
  template:   #template configuration to create pods
    metadata:
      labels:
        app: pod-info  #label name of pods
    spec:
      containers:
      - name: pod-info-container
        image: kimschles/pod-info-app:latest
        ports:
        - containerPort: 3000   #extenal port , add this in service yaml too
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name  
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
            