apiVersion: v1
kind: Pod
metadata:
  name: kube-pod-with-pvc
  labels:
    app: kube-pod-with-pvc
spec:
  containers:
  - name: kube-pod-with-pvc
    image: rahulwagh17/kubernetes:jhooq-k8s-springboot
    ports:
      - containerPort: 8080
        name: www
    volumeMounts:                           ##where to mount the files
      - name: www-persistent-storage
        mountPath: /mnt/
  volumes:
    - name: www-persistent-storage
      persistentVolumeClaim:
        claimName: kube-pvc                  ##pvc name