apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pvc
spec:
  volumeName: kube-demo-pv             ##pv name
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi